- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.bhargavachiliveru.online
  tasks:
  - name: Install Mysql Server
    ansible.builtin.dnf:
      name: mysql-server 
      state: latest

      
  - name: Start and Enable service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: install mysql python dependencies
    ansible.builtin.pip:
      name:
      - PyMySql
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11
  


# check password is setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "Registerd Output: {{mysql_connection_output}}"
