- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.bhargavachiliveru.online
  tasks:
  - name: Install Mysql Server
    ansible.builtin.dnf:
      name: mysql-server 
      state: latest
